- hosts: all
  tasks: 
    - name: debug
      debug:
        msg: "This is project_2 main deployment playbook"

- hosts: all
  tasks:
  - import_role:
      name: service_A
      tasks_from: main.yml

- hosts: all
  tasks:
  - import_role:
      name: service_B
      tasks_from: main.yml
