---
# tasks file for service_A_role
- name: hello from service_A role
  debug:
    msg: "This is service_A role, version ***2*** on service_A role repository, with nothing particular of any particular project"
